sudo: required
language: bash

services:
- docker
  
script:
- docker-compose run --rm tunnelist npm ci
- docker-compose run --rm tunnelist npm run lint
- docker-compose run --rm tunnelist npm run test